[storage]
sqlite_db = ".tilda/db/tilda.db"

[api_keys]
open_ai_api_key = "<YOUR_OPEN_AI_API_KEY>"
claude_api_key = "<YOUR_CLAUDE_API_KEY>"
gemini_api_key = "<YOUR_GEMINI_API_KEY>"
mistral_api_key = "<YOUR_MISTRAL_API_KEY>"
groq_api_key = "<YOUR_GROQ_API_KEY>"

[api_endpoints]
ollama = "http://127.0.0.1:11434"

[commands.terminal]
base_model = "gpt-3.5-turbo-0125"
token_encoding = "cl100k_base"
